"""modelo de dados completo

Revision ID: 47f79baac7ca
Revises: 
Create Date: 2026-09-11 23:56:40.098720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47f79baac7ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'PASSWORD_CHANGE', 'INVITE_SENT', 'PERMISSION_GRANTED', 'PERMISSION_REVOKED', 'EXTERNAL_OBSERVATION_RECORDED', 'RESTRICTED_DATA_ACCESS_DENIED', 'PLAN_CHANGED', 'CRITICAL_ALERT', 'DATA_EXPORTED', 'ACCOUNT_DELETION_REQUESTED', 'SUSPECTED_SESSION_THEFT', name='auditaction'), nullable=False),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_user_id'), 'audit_logs', ['target_user_id'], unique=False)
    op.create_table('baselines',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('indicator_key', sa.Enum('SLEEP_HOURS', 'WAKE_TIME_MINUTES', 'SLEEP_TIME_MINUTES', 'MOOD', 'ENERGY', 'ANXIETY', 'ABILITY_TO_START_TASKS', 'TASKS_STARTED_COUNT', 'TASKS_POSTPONED_COUNT', 'TASKS_COMPLETED_COUNT', 'LEFT_HOME', 'SOCIAL_CONTACT', 'ACTIVITY_LEVEL', 'AVOIDANCE_LOAD', 'MEDICATION_ADHERENCE', name='indicatorkey'), nullable=False),
    sa.Column('source', sa.Enum('SELF_DECLARED', 'OBSERVED', 'HYBRID', name='baselinesource'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', name='baselinestatus'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baselines_indicator_key'), 'baselines', ['indicator_key'], unique=False)
    op.create_index(op.f('ix_baselines_status'), 'baselines', ['status'], unique=False)
    op.create_index(op.f('ix_baselines_user_id'), 'baselines', ['user_id'], unique=False)
    op.create_table('daily_checkins',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('anxiety', sa.Integer(), nullable=True),
    sa.Column('ability_to_start_tasks', sa.Integer(), nullable=True),
    sa.Column('willingness_to_interact', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('sense_of_functioning', sa.Integer(), nullable=True),
    sa.Column('extra_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'checkin_date', name='uq_checkin_user_date')
    )
    op.create_index(op.f('ix_daily_checkins_checkin_date'), 'daily_checkins', ['checkin_date'], unique=False)
    op.create_index(op.f('ix_daily_checkins_user_id'), 'daily_checkins', ['user_id'], unique=False)
    op.create_table('deviation_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('engine', sa.Enum('EXECUTIVE', 'AVOIDANCE', 'ACTIVATION', 'STABILITY', name='deviationengine'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('domains_count', sa.Integer(), nullable=False),
    sa.Column('convergence_score', sa.Float(), nullable=True),
    sa.Column('triggering_indicator_keys', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('baseline_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deviation_events_detected_at'), 'deviation_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_deviation_events_engine'), 'deviation_events', ['engine'], unique=False)
    op.create_index(op.f('ix_deviation_events_user_id'), 'deviation_events', ['user_id'], unique=False)
    op.create_table('functional_indicators',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('indicator_key', sa.Enum('SLEEP_HOURS', 'WAKE_TIME_MINUTES', 'SLEEP_TIME_MINUTES', 'MOOD', 'ENERGY', 'ANXIETY', 'ABILITY_TO_START_TASKS', 'TASKS_STARTED_COUNT', 'TASKS_POSTPONED_COUNT', 'TASKS_COMPLETED_COUNT', 'LEFT_HOME', 'SOCIAL_CONTACT', 'ACTIVITY_LEVEL', 'AVOIDANCE_LOAD', 'MEDICATION_ADHERENCE', name='indicatorkey'), nullable=False),
    sa.Column('source', sa.Enum('CHECKIN', 'TASK_EVENT', 'ROUTINE', 'OBSERVATION', 'MEDICATION_EVENT', 'DERIVED', name='indicatorsource'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('recorded_for_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'indicator_key', 'recorded_for_date', 'source', name='uq_indicator_user_key_date_source')
    )
    op.create_index(op.f('ix_functional_indicators_indicator_key'), 'functional_indicators', ['indicator_key'], unique=False)
    op.create_index(op.f('ix_functional_indicators_recorded_for_date'), 'functional_indicators', ['recorded_for_date'], unique=False)
    op.create_index(op.f('ix_functional_indicators_user_id'), 'functional_indicators', ['user_id'], unique=False)
    op.create_table('life_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('TRAVEL', 'VACATION', 'NEW_JOB', 'ILLNESS', 'MOVE', 'OTHER', name='lifeeventtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_events_user_id'), 'life_events', ['user_id'], unique=False)
    op.create_table('medications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('dosage_note', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('discontinued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_user_id'), 'medications', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('max_notifications_per_day', sa.Integer(), nullable=True),
    sa.Column('channel_by_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('REMINDER', 'CHECKIN_REQUEST', 'TASK', 'SUPPORT_REQUEST', 'OBSERVATION', 'RELEVANT_CHANGE', 'ALERT', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('PUSH', 'EMAIL', 'IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='notificationpriority'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grouped_with', sa.UUID(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grouped_with'], ['notifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('personal_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_plans_user_id'), 'personal_plans', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('tone_preference', sa.Enum('QUASE_VAZIO', 'COMPANHEIRO_CALMO', name='tonestyle'), nullable=False),
    sa.Column('main_responsibilities', sa.Text(), nullable=True),
    sa.Column('work_or_study', sa.Text(), nullable=True),
    sa.Column('habits', sa.Text(), nullable=True),
    sa.Column('patterns_considered_normal', sa.Text(), nullable=True),
    sa.Column('recurring_difficulties', sa.Text(), nullable=True),
    sa.Column('self_recognized_warning_signs', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('privacy_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('routines',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('typical_wake_time', sa.Time(), nullable=True),
    sa.Column('typical_sleep_time', sa.Time(), nullable=True),
    sa.Column('goes_out_on_weekdays', sa.Boolean(), nullable=True),
    sa.Column('social_contact_days_per_week', sa.Integer(), nullable=True),
    sa.Column('typical_tasks_postponed_on_good_day', sa.Integer(), nullable=True),
    sa.Column('selected_activation_domains', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_user_id'), 'routines', ['user_id'], unique=False)
    op.create_table('trusted_person_relationships',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('trusted_user_id', sa.UUID(), nullable=True),
    sa.Column('invite_email', sa.String(length=320), nullable=False),
    sa.Column('invite_token', sa.String(length=128), nullable=False),
    sa.Column('relationship_label', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', name='relationshipstatus'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trusted_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token'),
    sa.UniqueConstraint('owner_user_id', 'trusted_user_id', name='uq_relationship_owner_trusted')
    )
    op.create_index(op.f('ix_trusted_person_relationships_owner_user_id'), 'trusted_person_relationships', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_trusted_person_relationships_trusted_user_id'), 'trusted_person_relationships', ['trusted_user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('GREEN', 'YELLOW', 'RED', name='alertstate'), nullable=False),
    sa.Column('triggering_deviation_id', sa.UUID(), nullable=True),
    sa.Column('reason_summary', sa.Text(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggering_deviation_id'], ['deviation_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_state'), 'alerts', ['state'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('baseline_metrics',
    sa.Column('baseline_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('median', sa.Float(), nullable=True),
    sa.Column('stddev', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('trend_slope', sa.Float(), nullable=True),
    sa.Column('recent_value', sa.Float(), nullable=True),
    sa.Column('diff_from_baseline', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baseline_metrics_baseline_id'), 'baseline_metrics', ['baseline_id'], unique=False)
    op.create_table('medication_schedules',
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('weekdays', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_schedules_medication_id'), 'medication_schedules', ['medication_id'], unique=False)
    op.create_table('observations',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('relationship_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ISOLAMENTO', 'AUSENCIA_TRABALHO', 'AUSENCIA_ESTUDOS', 'MUDANCA_SONO', 'AUTOCUIDADO_REDUZIDO', 'COMUNICACAO_REDUZIDA', 'MUDANCA_INCOMUM', 'IRRITABILIDADE', 'DIFICULDADE_FUNCIONAR', 'AUSENCIA', 'OUTRO', name='observationcategory'), nullable=False),
    sa.Column('since', sa.Enum('HOJE', 'DOIS_A_TRES_DIAS', 'MAIS_DE_TRES_DIAS', name='observationsince'), nullable=False),
    sa.Column('intensity', sa.Enum('LEVE', 'RELEVANTE', 'SERIA', name='observationintensity'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['trusted_person_relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_owner_user_id'), 'observations', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_observations_relationship_id'), 'observations', ['relationship_id'], unique=False)
    op.create_table('permissions',
    sa.Column('relationship_id', sa.UUID(), nullable=False),
    sa.Column('permission_key', sa.Enum('RECORD_OBSERVATION', 'SUGGEST_TASK', 'CREATE_TASK', 'HELP_WITH_TASK', 'CONFIRM_EVENT', 'REQUEST_CHECKIN', 'RECEIVE_ALERT_YELLOW', 'RECEIVE_ALERT_RED', 'VIEW_ROUTINE', 'VIEW_MEDICATION', 'VIEW_SPECIFIC_INDICATORS', 'VIEW_FULL_HISTORY', 'ACCESS_CRISIS_PLAN', name='permissionkey'), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.Column('indicator_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['trusted_person_relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_id', 'permission_key', name='uq_permission_relationship_key')
    )
    op.create_index(op.f('ix_permissions_relationship_id'), 'permissions', ['relationship_id'], unique=False)
    op.create_table('personal_plan_rules',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('signal_key', sa.Enum('FALTAS', 'ISOLAMENTO', 'SONO', 'MEDICACAO', 'ABANDONO_DE_TAREFAS', 'USO_DE_SUBSTANCIAS', 'COMUNICACAO', 'AUTOCUIDADO', name='personalplansignal'), nullable=False),
    sa.Column('threshold_description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['personal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_plan_rules_plan_id'), 'personal_plan_rules', ['plan_id'], unique=False)
    op.create_table('routine_events',
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('changed_field', sa.String(length=80), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_events_routine_id'), 'routine_events', ['routine_id'], unique=False)
    op.create_table('tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'PAUSED', 'POSTPONED', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('postponed_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('SELF', 'TRUSTED_PERSON_SUGGESTION', name='taskorigin'), nullable=False),
    sa.Column('source_relationship_id', sa.UUID(), nullable=True),
    sa.Column('support_relationship_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_relationship_id'], ['trusted_person_relationships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['support_relationship_id'], ['trusted_person_relationships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('interventions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('MICROINTERVENTION', 'BODY_DOUBLING_SESSION', name='interventiontype'), nullable=False),
    sa.Column('status', sa.Enum('SUGGESTED', 'REQUESTED', 'ACCEPTED', 'STARTED', 'FINISHED', 'DISMISSED', name='interventionstatus'), nullable=False),
    sa.Column('related_task_id', sa.UUID(), nullable=True),
    sa.Column('related_deviation_id', sa.UUID(), nullable=True),
    sa.Column('support_relationship_id', sa.UUID(), nullable=True),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_deviation_id'], ['deviation_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['support_relationship_id'], ['trusted_person_relationships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_support_relationship_id'), 'interventions', ['support_relationship_id'], unique=False)
    op.create_index(op.f('ix_interventions_user_id'), 'interventions', ['user_id'], unique=False)
    op.create_table('medication_events',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('TAKEN', 'NOT_TAKEN', 'FORGOT_TO_CONFIRM', 'SKIPPED_DELIBERATELY', 'UNAVAILABLE', name='medicationeventstatus'), nullable=False),
    sa.Column('skip_reason', sa.Enum('ESQUECI', 'ROTINA_MUDOU', 'NAO_CONSEGUI_LEVANTAR', 'EFEITO_ADVERSO', 'MEDO', 'MEDICAMENTO_INDISPONIVEL', 'DECISAO_PROPRIA', 'OUTRO', name='medicationskipreason'), nullable=True),
    sa.Column('custom_reason_text', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_events_schedule_id'), 'medication_events', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_medication_events_scheduled_for'), 'medication_events', ['scheduled_for'], unique=False)
    op.create_table('task_events',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'STARTED', 'PAUSED', 'POSTPONED', 'RESUMED', 'COMPLETED', 'CANCELLED', name='taskeventtype'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_table('intervention_results',
    sa.Column('intervention_id', sa.UUID(), nullable=False),
    sa.Column('helped', sa.Boolean(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intervention_id')
    )
    op.create_table('task_failure_reasons',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('ESQUECI', 'NAO_CONSEGUI_COMECAR', 'FIQUEI_ANSIOSO', 'NAO_TIVE_ENERGIA', 'NAO_QUERIA_ENFRENTAR', 'ME_DISTRAI', 'NAO_TIVE_TEMPO', 'TAREFA_GRANDE_DEMAIS', 'PRIORIDADE_MUDOU', 'OUTRO', name='taskfailurereasontype'), nullable=False),
    sa.Column('custom_text', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['task_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_task_failure_reasons_task_id'), 'task_failure_reasons', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_failure_reasons_task_id'), table_name='task_failure_reasons')
    op.drop_table('task_failure_reasons')
    op.drop_table('intervention_results')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_medication_events_scheduled_for'), table_name='medication_events')
    op.drop_index(op.f('ix_medication_events_schedule_id'), table_name='medication_events')
    op.drop_table('medication_events')
    op.drop_index(op.f('ix_interventions_user_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_support_relationship_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_routine_events_routine_id'), table_name='routine_events')
    op.drop_table('routine_events')
    op.drop_index(op.f('ix_personal_plan_rules_plan_id'), table_name='personal_plan_rules')
    op.drop_table('personal_plan_rules')
    op.drop_index(op.f('ix_permissions_relationship_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_observations_owner_user_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_relationship_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_medication_schedules_medication_id'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    op.drop_index(op.f('ix_baseline_metrics_baseline_id'), table_name='baseline_metrics')
    op.drop_table('baseline_metrics')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_state'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_trusted_person_relationships_trusted_user_id'), table_name='trusted_person_relationships')
    op.drop_index(op.f('ix_trusted_person_relationships_owner_user_id'), table_name='trusted_person_relationships')
    op.drop_table('trusted_person_relationships')
    op.drop_index(op.f('ix_routines_user_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_personal_plans_user_id'), table_name='personal_plans')
    op.drop_table('personal_plans')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_medications_user_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_life_events_user_id'), table_name='life_events')
    op.drop_table('life_events')
    op.drop_index(op.f('ix_functional_indicators_user_id'), table_name='functional_indicators')
    op.drop_index(op.f('ix_functional_indicators_recorded_for_date'), table_name='functional_indicators')
    op.drop_index(op.f('ix_functional_indicators_indicator_key'), table_name='functional_indicators')
    op.drop_table('functional_indicators')
    op.drop_index(op.f('ix_deviation_events_user_id'), table_name='deviation_events')
    op.drop_index(op.f('ix_deviation_events_engine'), table_name='deviation_events')
    op.drop_index(op.f('ix_deviation_events_detected_at'), table_name='deviation_events')
    op.drop_table('deviation_events')
    op.drop_index(op.f('ix_daily_checkins_user_id'), table_name='daily_checkins')
    op.drop_index(op.f('ix_daily_checkins_checkin_date'), table_name='daily_checkins')
    op.drop_table('daily_checkins')
    op.drop_index(op.f('ix_baselines_user_id'), table_name='baselines')
    op.drop_index(op.f('ix_baselines_status'), table_name='baselines')
    op.drop_index(op.f('ix_baselines_indicator_key'), table_name='baselines')
    op.drop_table('baselines')
    op.drop_index(op.f('ix_audit_logs_target_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # O autogenerate do Alembic não remove tipos ENUM nativos do
    # Postgres ao derrubar as tabelas que os usam (limitação
    # conhecida) — sem isso, um downgrade seguido de upgrade falha
    # com "type already exists". Removidos explicitamente aqui, na
    # ordem inversa da criação, todos como CASCADE-safe (checkfirst).
    enum_names = [
        "auditaction", "baselinesource", "baselinestatus", "deviationengine",
        "indicatorkey", "indicatorsource", "alertstate", "interventionstatus",
        "interventiontype", "medicationeventstatus", "medicationskipreason",
        "notificationchannel", "notificationpriority", "notificationtype",
        "observationcategory", "observationintensity", "observationsince",
        "permissionkey", "personalplansignal", "relationshipstatus",
        "taskeventtype", "taskfailurereasontype", "taskorigin", "taskpriority",
        "taskstatus", "tonestyle", "lifeeventtype",
    ]
    for name in enum_names:
        op.execute(f"DROP TYPE IF EXISTS {name}")
